### ISSUE TITLE
Inconsistency in the number of posts on the "watch" page

### ISSUE THREAD

**Issue by Aivean** [spaceshelter/orbitar#121]
<img width="81" alt="image" src="https://user-images.githubusercontent.com/2865203/186076810-096f48f3-40a0-41dc-ac48-b48a1e1b7367.png">

People are reporting "fire" showing a number of unread posts, while the "unread" page doesn't show anything. 
Probably an error in SQL. Need to reproduce.

**Comment by Alao-Abiodun** [comment]
Hello @Aivean I did like to work on this issue this is my first time contributing to open source and I will be glad if you guide me on how to make my first PR but I am good with git and Github. Reading through the comment you gave saying the error is probably from SQL and I am quite familiar with SQL queries.

**Comment by Aivean** [comment]
Context:

> По поводу цифры с новыми каментами, я кажется понял откуда она, похоже в неё входят новые каменты в тредах где была нажата кнопка "отслеживать". Но не все, а видимо только те в которых не было ни одного камента на момент включения "отслеживания". Эти посты почему-то не попадают в список "непрочитанные", но живут себе спокойно в списке "все". И раньше видимо эта цифра собиралась из списка в непрочитанных, а теперь из списка всех. Такие дела.

Translation:

"Watch" number includes new comments in "watched" posts, but only in those posts, that didn't have any comments at the moment when "watch button" was pressed. Such posts don't show up on "Watch" page, but are present in the "All" feed.

Could be related: #100
