### ISSUE TITLE
Caddy doesn't restart on config changes

### ISSUE THREAD

**Issue by Lexy2** [spaceshelter/orbitar#188]
When debugging locally or in general, you might want to modify `Caddyfile`.

Caddy should watch changes in the file and apply them immediately instead of requiring a manual container restart.

**Comment by Aivean** [comment]
> Caddy should watch changes in the file and apply them immediately instead of requiring a manual container restart.

Could be related to the docker volumes. E.g. when I encountered this issue on staging, I looked at the `Caddyfile` in local git checkout (it had the latests changes), but when I attached to the running `caddy` container and checked its corresponding mounted `/etc/caddy/Caddyfile`, it had the outdated version. 

Not sure what's going on.

**Comment by Lexy2** [comment]
> Not sure what's going on.

It's exactly the volumes. The running configuration is based on the volumes either from the test runs or my home dir, or anything random when the volumes were recreated.
You can confirm it by inspecting the running container.

We should fix it some day.

**Comment by Aivean** [comment]
But do you have an understanding how to force volume recreation in the docker-compose?

**Comment by Lexy2** [comment]
> But do you have an understanding how to force volume recreation in the docker-compose?

`docker-compose down -v -f`?

**Comment by Aivean** [comment]
Doesn't it work only for the named volumes?  Are we talking about this volume?
```
    volumes:
      - $PWD/caddy/Caddyfile.local:/etc/caddy/Caddyfile
```
