### ISSUE TITLE
relative date is calculated incorrectly

### ISSUE THREAD

**Issue by 4vanger** [spaceshelter/orbitar#251]
I'm in PST, local time 7:34. Commen on screenshot was created 6 minutes ago.
Actual: "Вчера в 7:28"
Expected: "Сегодня в 7:28"
<img width="235" alt="image" src="https://user-images.githubusercontent.com/596990/211595185-84d497fd-d95e-4aee-ba9d-62d79347c81d.png">

**Comment by Aivean** [comment]
Fixed in #298
